# Generated by Django 4.2 on 2023-05-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_second_name_alter_customer_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='second_name',
            new_name='Second_Name',
        ),
    ]
