# Generated by Django 4.2 on 2023-05-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_first_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('Dispense_date', models.DateField()),
                ('Pharmacist_ID', models.IntegerField()),
                ('Prescription_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Med_Name', models.DateField()),
                ('Manufacturer', models.IntegerField()),
                ('Supplier', models.IntegerField()),
                ('Strength', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Dosage_form', models.CharField(max_length=50)),
                ('Expiration_date', models.DateField()),
                ('Amount', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dispense')),
            ],
        ),
    ]
