# Generated by Django 4.2 on 2023-05-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dispense_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='code',
            field=models.CharField(max_length=4),
        ),
    ]
