# Generated by Django 4.2 on 2023-05-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_medication_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='customer_condition',
            old_name='code',
            new_name='Code',
        ),
    ]
