# Generated by Django 4.2 on 2023-05-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_code_customer_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_condition',
            old_name='Code',
            new_name='Customer',
        ),
    ]
