# Generated by Django 4.2 on 2023-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_code_customer_condition_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
